### ISSUE TITLE
Resol VBUS-LAN-Adapter: Home Assistant zeigt keine neuen Daten mehr an

### ISSUE THREAD

**Issue by hoppel118** [dm82m/hass-Deltasol-KM2#30]
Moin Dirk,

seit letzter Woche werden die Daten meines Resol VBUS-LAN-Adapters in Home Assistant nicht mehr aktualisiert.

Ich habe keine Ahnung, was dazu geführt haben könnte.

* Home Assistant 2023.3.5
* Supervisor 2023.03.1
* Operating System 9.5
* Frontend 20230309.1 - latest
* Resol-VBus Addon: 0.0.5
* Resol KM2, DL2/DL3, VBus/LAN, VBus/USB HACS Integration: 0.3.1

Wenn ich folgenden Befehl per SSH auf meinem HAOS oder einem anderen Gerät im Netzwerk ausführe, sehe ich folgende Daten:

```
[core-ssh ~]$ curl -s http://homeassistant.home.arpa:3333/api/v1/live-data
[
    {
        "id": "00_0010_7321_10_0100_000_2_0",
        "name": "Temperature sensor 1",
        "rawValue": 16.3
    },
    {
        "id": "00_0010_7321_10_0100_002_2_0",
        "name": "Temperature sensor 2",
        "rawValue": 11.8
    },
    {
        "id": "00_0010_7321_10_0100_004_2_0",
        "name": "Temperature sensor 3",
        "rawValue": 20.6
    },
    {
        "id": "00_0010_7321_10_0100_006_2_0",
        "name": "Temperature sensor 4",
        "rawValue": 56.300000000000004
    },
    {
        "id": "00_0010_7321_10_0100_008_2_0",
        "name": "Temperature sensor 5",
        "rawValue": 888.8000000000001
    },
    {
        "id": "00_0010_7321_10_0100_010_2_0",
        "name": "Temperature sensor 6",
        "rawValue": 888.8000000000001
    },
    {
        "id": "00_0010_7321_10_0100_012_2_0",
        "name": "Temperature sensor 7",
        "rawValue": 888.8000000000001
    },
    {
        "id": "00_0010_7321_10_0100_014_2_0",
        "name": "Temperature sensor 8",
        "rawValue": 888.8000000000001
    },
    {
        "id": "00_0010_7321_10_0100_016_2_0",
        "name": "Temperature sensor 9",
        "rawValue": 888.8000000000001
    },
    {
        "id": "00_0010_7321_10_0100_018_2_0",
        "name": "Temperature sensor 10",
        "rawValue": 888.8000000000001
    },
    {
        "id": "00_0010_7321_10_0100_020_2_0",
        "name": "Temperature sensor 11",
        "rawValue": 888.8000000000001
    },
    {
        "id": "00_0010_7321_10_0100_022_2_0",
        "name": "Temperature sensor 12",
        "rawValue": 888.8000000000001
    },
    {
        "id": "00_0010_7321_10_0100_024_2_0",
        "name": "Irradiation",
        "rawValue": 0
    },
    {
        "id": "00_0010_7321_10_0100_028_4_0",
        "name": "Impulse input 1",
        "rawValue": 0
    },
    {
        "id": "00_0010_7321_10_0100_032_4_0",
        "name": "Impulse input 2",
        "rawValue": 0
    },
    {
        "id": "00_0010_7321_10_0100_036_2_0",
        "name": "Sensor line break mask",
        "rawValue": 4080
    },
    {
        "id": "00_0010_7321_10_0100_038_2_0",
        "name": "Sensor short-circuit mask",
        "rawValue": 0
    },
    {
        "id": "00_0010_7321_10_0100_040_2_0",
        "name": "Sensor usage mask",
        "rawValue": 3
    },
    {
        "id": "00_0010_7321_10_0100_044_1_0",
        "name": "Pump speed relay 1",
        "rawValue": 0
    },
    {
        "id": "00_0010_7321_10_0100_045_1_0",
        "name": "Pump speed relay 2",
        "rawValue": 0
    },
    {
        "id": "00_0010_7321_10_0100_046_1_0",
        "name": "Pump speed relay 3",
        "rawValue": 0
    },
    {
        "id": "00_0010_7321_10_0100_047_1_0",
        "name": "Pump speed relay 4",
        "rawValue": 0
    },
    {
        "id": "00_0010_7321_10_0100_048_1_0",
        "name": "Pump speed relay 5",
        "rawValue": 0
    },
    {
        "id": "00_0010_7321_10_0100_049_1_0",
        "name": "Pump speed relay 6",
        "rawValue": 0
    },
    {
        "id": "00_0010_7321_10_0100_050_1_0",
        "name": "Pump speed relay 7",
        "rawValue": 0
    },
    {
        "id": "00_0010_7321_10_0100_051_1_0",
        "name": "Pump speed relay 8",
        "rawValue": 0
    },
    {
        "id": "00_0010_7321_10_0100_052_1_0",
        "name": "Pump speed relay 9",
        "rawValue": 0
    },
    {
        "id": "00_0010_7321_10_0100_058_2_0",
        "name": "Relay usage mask",
        "rawValue": 1
    },
    {
        "id": "00_0010_7321_10_0100_060_2_0",
        "name": "Error mask",
        "rawValue": 0
    },
    {
        "id": "00_0010_7321_10_0100_062_2_0",
        "name": "Warning mask",
        "rawValue": 0
    },
    {
        "id": "00_0010_7321_10_0100_064_2_0",
        "name": "Controller version",
        "rawValue": 258
    },
    {
        "id": "00_0010_7321_10_0100_066_2_0",
        "name": "System time",
        "rawValue": 1043
    },
    {
        "id": "00_0010_7326_10_0100_000_2_0",
        "name": "Flow temperature",
        "rawValue": 16.3
    },
    {
        "id": "00_0010_7326_10_0100_002_2_0",
        "name": "Return temperature",
        "rawValue": 11.8
    },
    {
        "id": "00_0010_7326_10_0100_004_2_0",
        "name": "Flow rate",
        "rawValue": 0
    },
    {
        "id": "00_0010_7326_10_0100_006_2_0",
        "name": "Heat",
        "rawValue": 5612563
```

Wenn ich ein paar Minuten warte und denselben Befehl erneut ausführe, sehe ich dass sich die Werte verändern.

Diese Werte sind allerdings in der Homeassistant History nicht mehr sichtbar.

![screenshot_1333](https://user-images.githubusercontent.com/991344/226405784-da321d57-15af-4d7f-9f8b-1174210013c9.png)

Im HomeAssistant Logfile sehe ich folgende Einträge:

```
Log Details (ERROR)
This error originated from a custom integration.
Logger: custom_components.deltasol
Source: custom_components/deltasol/deltasolapi.py:89
Integration: deltasol ([documentation](https://github.com/dm82m/hass-deltasol-KM2), [issues](https://github.com/dm82m/hass-deltasol-KM2/issues))
First occurred: March 19, 2023 at 6:56:33 PM (1 occurrences)
Last logged: March 19, 2023 at 6:56:33 PM

Error detecting Resol product - HTTPConnectionPool(host='127.0.0.1', port=3333): Max retries exceeded with url: /cgi-bin/get_resol_device_information (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faf97777400>: Failed to establish a new connection: [Errno 111] Connection refused')), please file an issue at: https://github.com/dm82m/hass-Deltasol-KM2/issues/new/choose
```

```
Log Details (ERROR)
This error originated from a custom integration.
Logger: custom_components.deltasol
Source: custom_components/deltasol/sensor.py:95
Integration: deltasol ([documentation](https://github.com/dm82m/hass-deltasol-KM2), [issues](https://github.com/dm82m/hass-deltasol-KM2/issues))
First occurred: March 19, 2023 at 6:56:33 PM (1 occurrences)
Last logged: March 19, 2023 at 6:56:33 PM

Stopping Resol integration due to previous error: Error detecting Resol product - HTTPConnectionPool(host='127.0.0.1', port=3333): Max retries exceeded with url: /cgi-bin/get_resol_device_information (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faf97777400>: Failed to establish a new connection: [Errno 111] Connection refused')), please file an issue at: https://github.com/dm82m/hass-Deltasol-KM2/issues/new/choose
```

```
Log Details (ERROR)
This error originated from a custom integration.
Logger: custom_components.deltasol
Source: custom_components/deltasol/deltasolapi.py:80
Integration: deltasol ([documentation](https://github.com/dm82m/hass-deltasol-KM2), [issues](https://github.com/dm82m/hass-deltasol-KM2/issues))
First occurred: March 19, 2023 at 6:56:33 PM (1 occurrences)
Last logged: March 19, 2023 at 6:56:33 PM

Unexpected error fetching deltasol_sensor data: Error detecting Resol product - HTTPConnectionPool(host='127.0.0.1', port=3333): Max retries exceeded with url: /cgi-bin/get_resol_device_information (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faf97777400>: Failed to establish a new connection: [Errno 111] Connection refused')), please file an issue at: https://github.com/dm82m/hass-Deltasol-KM2/issues/new/choose
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7faf97777400>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=3333): Max retries exceeded with url: /cgi-bin/get_resol_device_information (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faf97777400>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/deltasol/deltasolapi.py", line 61, in detect_product
    response = requests.request("GET", url)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=3333): Max retries exceeded with url: /cgi-bin/get_resol_device_information (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faf97777400>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 195, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/deltasol/sensor.py", line 83, in async_update_data
    raise error
  File "/config/custom_components/deltasol/sensor.py", line 79, in async_update_data
    data = await hass.async_add_executor_job(api.fetch_data)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/deltasol/deltasolapi.py", line 104, in fetch_data
    raise error
  File "/config/custom_components/deltasol/deltasolapi.py", line 89, in fetch_data
    product = self.detect_product()
  File "/config/custom_components/deltasol/deltasolapi.py", line 80, in detect_product
    raise IntegrationError(error)
homeassistant.exceptions.IntegrationError: Error detecting Resol product - HTTPConnectionPool(host='127.0.0.1', port=3333): Max retries exceeded with url: /cgi-bin/get_resol_device_information (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faf97777400>: Failed to establish a new connection: [Errno 111] Connection refused')), please file an issue at: https://github.com/dm82m/hass-Deltasol-KM2/issues/new/choose
```

```
Log Details (ERROR)
Logger: homeassistant.components.sensor
Source: custom_components/deltasol/sensor.py:58
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: March 19, 2023 at 6:56:33 PM (1 occurrences)
Last logged: March 19, 2023 at 6:56:33 PM

Error while setting up deltasol platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/deltasol/sensor.py", line 98, in async_setup_platform
    await update_unique_ids(hass, coordinator.data)
  File "/config/custom_components/deltasol/sensor.py", line 58, in update_unique_ids
    for unique_id, endpoint in data.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

Hast du eine Idee, woran das liegt?

Danke und Gruß Hoppel

**Comment by hoppel118** [comment]
Hi Dirk,

habe gerade mein HAOS geupdated:

* Home Assistant 2023.3.6
* Supervisor 2023.03.2
* Operating System 9.5
* Frontend 20230309.1 - latest

Nun läuft plötzlich wieder alles so…

Keine Ahnung, was da mit dem letzten Update schief gegangen ist. 😃

Gruß Hoppel

**Comment by hoppel118** [comment]
Moin Dirk,

das Problem ist wieder aufgetaucht. Musste heute morgen mein Home Assistant einmal neustarten. Anschließend haben sich die Daten meines Resol VBUS-LAN-Adapters nicht mehr aktualisiert und folgende Meldungen tauchten im Log auf:

```
Log Details (ERROR)
This error originated from a custom integration.
Logger: custom_components.deltasol
Source: custom_components/deltasol/deltasolapi.py:89
Integration: deltasol ([documentation](https://github.com/dm82m/hass-deltasol-KM2), [issues](https://github.com/dm82m/hass-deltasol-KM2/issues))
First occurred: 7:43:32 PM (1 occurrences)
Last logged: 7:43:32 PM

Error detecting Resol product - HTTPConnectionPool(host='127.0.0.1', port=3333): Max retries exceeded with url: /cgi-bin/get_resol_device_information (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7f1d130730>: Failed to establish a new connection: [Errno 111] Connection refused')), please file an issue at: https://github.com/dm82m/hass-Deltasol-KM2/issues/new/choose
```

```
Log Details (ERROR)
This error originated from a custom integration.
Logger: custom_components.deltasol
Source: custom_components/deltasol/sensor.py:95
Integration: deltasol ([documentation](https://github.com/dm82m/hass-deltasol-KM2), [issues](https://github.com/dm82m/hass-deltasol-KM2/issues))
First occurred: 7:43:32 PM (1 occurrences)
Last logged: 7:43:32 PM

Stopping Resol integration due to previous error: Error detecting Resol product - HTTPConnectionPool(host='127.0.0.1', port=3333): Max retries exceeded with url: /cgi-bin/get_resol_device_information (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7f1d130730>: Failed to establish a new connection: [Errno 111] Connection refused')), please file an issue at: https://github.com/dm82m/hass-Deltasol-KM2/issues/new/choose

```

Wo ich hier gerade "Max retries exceeded" lese... Kann es sein, dass das Addon noch nicht fertig geladen ist und deine HACS Integration dann abbricht, wenn das Addon nicht bereit ist.

Meinen VBUS-LAN-Adapter kann ich anpingen und das WebInterface ist auch erreichbar.

Über die v2 Api werden weiterhin die Werte aktualisiert

Um 23:13 Uhr hat die Api folgendes geliefert:

```
curl -s http://homeassistant.home.arpa:3333/api/v2/live-data | head -n 50
[
    {
        "id": "00_0010_7321_10_0100_000_2_0",
        "name": "Temperature sensor 1",
        "rawValue": 4.1000000000000005,
        "unitCode": "DegreesCelsius",
        "unitFamily": "Temperature",
        "unitText": " °C"
    },
    {
        "id": "00_0010_7321_10_0100_002_2_0",
        "name": "Temperature sensor 2",
        "rawValue": 12.700000000000001,
        "unitCode": "DegreesCelsius",
        "unitFamily": "Temperature",
        "unitText": " °C"
    },
    {
        "id": "00_0010_7321_10_0100_004_2_0",
        "name": "Temperature sensor 3",
        "rawValue": 35.9,
        "unitCode": "DegreesCelsius",
        "unitFamily": "Temperature",
        "unitText": " °C"
    },
    {
        "id": "00_0010_7321_10_0100_006_2_0",
        "name": "Temperature sensor 4",
        "rawValue": 64,
        "unitCode": "DegreesCelsius",
        "unitFamily": "Temperature",
        "unitText": " °C"
    },
    {
        "id": "00_0010_7321_10_0100_008_2_0",
        "name": "Temperature sensor 5",
        "rawValue": 888.8000000000001,
        "unitCode": "DegreesCelsius",
        "unitFamily": "Temperature",
        "unitText": " °C"
    },
    {
        "id": "00_0010_7321_10_0100_010_2_0",
        "name": "Temperature sensor 6",
        "rawValue": 888.8000000000001,
        "unitCode": "DegreesCelsius",
        "unitFamily": "Temperature",
        "unitText": " °C"
    },
```

Um 23:20 Uhr hat die Api folgendes geliefert:

```
curl -s http://homeassistant.home.arpa:3333/api/v2/live-data | head -n 50
[
    {
        "id": "00_0010_7321_10_0100_000_2_0",
        "name": "Temperature sensor 1",
        "rawValue": 4.1000000000000005,
        "unitCode": "DegreesCelsius",
        "unitFamily": "Temperature",
        "unitText": " °C"
    },
    {
        "id": "00_0010_7321_10_0100_002_2_0",
        "name": "Temperature sensor 2",
        "rawValue": 12.8,
        "unitCode": "DegreesCelsius",
        "unitFamily": "Temperature",
        "unitText": " °C"
    },
    {
        "id": "00_0010_7321_10_0100_004_2_0",
        "name": "Temperature sensor 3",
        "rawValue": 35.9,
        "unitCode": "DegreesCelsius",
        "unitFamily": "Temperature",
        "unitText": " °C"
    },
    {
        "id": "00_0010_7321_10_0100_006_2_0",
        "name": "Temperature sensor 4",
        "rawValue": 63.900000000000006,
        "unitCode": "DegreesCelsius",
        "unitFamily": "Temperature",
        "unitText": " °C"
    },
    {
        "id": "00_0010_7321_10_0100_008_2_0",
        "name": "Temperature sensor 5",
        "rawValue": 888.8000000000001,
        "unitCode": "DegreesCelsius",
        "unitFamily": "Temperature",
        "unitText": " °C"
    },
    {
        "id": "00_0010_7321_10_0100_010_2_0",
        "name": "Temperature sensor 6",
        "rawValue": 888.8000000000001,
        "unitCode": "DegreesCelsius",
        "unitFamily": "Temperature",
        "unitText": " °C"
    },
```

Die Daten werden also weiterhin vom VBUS-LAN-Adapter ausgelesen und aktualisiert über die API bereitgestellt.

Im Logfile sind außerdem noch folgende Einträge vorhanden:

```
Log Details (ERROR)
This error originated from a custom integration.
Logger: custom_components.deltasol
Source: custom_components/deltasol/deltasolapi.py:80
Integration: deltasol ([documentation](https://github.com/dm82m/hass-deltasol-KM2), [issues](https://github.com/dm82m/hass-deltasol-KM2/issues))
First occurred: 7:43:32 PM (1 occurrences)
Last logged: 7:43:32 PM

Unexpected error fetching deltasol_sensor data: Error detecting Resol product - HTTPConnectionPool(host='127.0.0.1', port=3333): Max retries exceeded with url: /cgi-bin/get_resol_device_information (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7f1d130730>: Failed to establish a new connection: [Errno 111] Connection refused')), please file an issue at: https://github.com/dm82m/hass-Deltasol-KM2/issues/new/choose
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f7f1d130730>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=3333): Max retries exceeded with url: /cgi-bin/get_resol_device_information (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7f1d130730>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/deltasol/deltasolapi.py", line 61, in detect_product
    response = requests.request("GET", url)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=3333): Max retries exceeded with url: /cgi-bin/get_resol_device_information (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7f1d130730>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 195, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/deltasol/sensor.py", line 83, in async_update_data
    raise error
  File "/config/custom_components/deltasol/sensor.py", line 79, in async_update_data
    data = await hass.async_add_executor_job(api.fetch_data)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/deltasol/deltasolapi.py", line 104, in fetch_data
    raise error
  File "/config/custom_components/deltasol/deltasolapi.py", line 89, in fetch_data
    product = self.detect_product()
  File "/config/custom_components/deltasol/deltasolapi.py", line 80, in detect_product
    raise IntegrationError(error)
homeassistant.exceptions.IntegrationError: Error detecting Resol product - HTTPConnectionPool(host='127.0.0.1', port=3333): Max retries exceeded with url: /cgi-bin/get_resol_device_information (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7f1d130730>: Failed to establish a new connection: [Errno 111] Connection refused')), please file an issue at: https://github.com/dm82m/hass-Deltasol-KM2/issues/new/choose
```

```
Log Details (ERROR)
Logger: homeassistant.components.sensor
Source: custom_components/deltasol/sensor.py:58
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 7:43:32 PM (1 occurrences)
Last logged: 7:43:32 PM

Error while setting up deltasol platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/deltasol/sensor.py", line 98, in async_setup_platform
    await update_unique_ids(hass, coordinator.data)
  File "/config/custom_components/deltasol/sensor.py", line 58, in update_unique_ids
    for unique_id, endpoint in data.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

Wäre cool, wenn du dir das nochmal genauer ansehen könntest.

Benötigst du noch weitere Informationen? Hast du evtl. eine Idee, was ich nochmal probieren könnte?

Danke und Gruß Hoppel

**Comment by dm82m** [comment]
Probier mal nur Home Assistant Neustarten, also Core und nicht den ganzen Server.

**Comment by hoppel118** [comment]
Jo, ich bin ja relativ neu bei Home Assistant und ich dachte, es macht wohl Sinn die gesamte virtuelle Maschine neuzustarten, was ich auch mehrfach erfolglos versucht habe.

Ich hatte sogar schon die Integration de- und neuinstalliert.

Aber du hast recht, wenn ich nicht das gesamte System, sondern nur Home Assistant neu starte, funktioniert es.

Das ist zumindest erstmal ein Workaround mit dem ich handlungsfähig bin.

Hast du eine Idee, wie man das dauerhaft lösen kann?

Danke dir

**Comment by dm82m** [comment]
Das problem ist, dass bei einem Neustart der gesamten virtuellen Maschine der Core Teil von HA schneller startet als die Addons.

Ideen hab ich schon, die Frage ist aber eher ob du nicht künftig deinen restart Workflow auf Ha Core beschränkst und das Problem damit für dich nicht mehr auftritt.

**Comment by hoppel118** [comment]
Ja, das werde ich Workaround-technisch auf jeden Fall erstmal so machen. Es gibt hier also überhaupt keinen Handlungsdruck. 😉

Ich schlage vor, dass wir das Ticket offen lassen bis du deine Ideen implementiert und ich sie erfolgreich getestet habe. Aber wie gesagt, das hat keine Eile. Ich weiß ja nun, was ich tun kann.

Gib einfach Bescheid, wenn ich etwas testen soll.

Danke dir und einen schönen Tag noch

**Comment by dm82m** [comment]
ich hab das erstmal nicht implementieren, schreibe aber mal meine gedanken auf:

- custom property um einen delay einzubauen für den integration start bei nutzung mit addon
- umstellen auf config flow, damit man per ui die integration neustarten kann und nicht HA core neustarten muss
- erhöhung der retries bei nutzung mit addon, ggf. timeout erhöhen, etc.

**Comment by hoppel118** [comment]
Das hört sich alles gut an! 😉

**Comment by dm82m** [comment]
das thema hier ist jetzt auch mit der 1.0.0 gefixt. falls zum resol gerät keine verbindung aufgebaut werden kann, wird es einfach immer wieder probiert, bis es dann geht.
