### ISSUE TITLE
This entity is no longer being provided by the deltasol integration. If the entity is no longer in use, delete it in settings.

### ISSUE THREAD

**Issue by evertterpstra** [dm82m/hass-Deltasol-KM2#38]
Resol KM1/KM2, DL2/DL3, VBus/LAN, VBus/USB
hass-Deltasol-KM2

Since three days I get this error with my Deltasol.
"This entity is no longer being provided by the deltasol integration. If the entity is no longer in use, delete it in settings."
I'm still using it............

Something happened? Problaby during update HA?
![foutmelding Deltasol](https://github.com/dm82m/hass-Deltasol-KM2/assets/123770708/82f0aac5-163b-4209-aa8a-d085e33ee3b9)

Thnxs Evert

**Comment by dm82m** [comment]
Please enable debug logging for the integration and share the logs here. I am on HA 2024.2.0 and everything is working.

**Comment by evertterpstra** [comment]
This error originated from a custom integration.

Logger: custom_components.deltasol
Source: helpers/update_coordinator.py:300
Integration: deltasol (documentation, issues)
First occurred: February 6, 2024 at 15:01:05 (1 occurrences)
Last logged: February 6, 2024 at 15:01:05

Unexpected error fetching deltasol_sensor data: Error detecting Resol product - HTTPConnectionPool(host='127.0.0.1', port=3333): Max retries exceeded with url: /cgi-bin/get_resol_device_information (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f45f88c6b90>: Failed to establish a new connection: [Errno 111] Connection refused')), please file an issue at: https://github.com/dm82m/hass-Deltasol-KM2/issues/new/choose
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.11/http/client.py", line 1286, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1332, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1041, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.11/http/client.py", line 979, in send
    self.connect()
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f45f88c6b90>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=3333): Max retries exceeded with url: /cgi-bin/get_resol_device_information (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f45f88c6b90>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/deltasol/deltasolapi.py", line 64, in detect_product
    response = requests.request("GET", url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=3333): Max retries exceeded with url: /cgi-bin/get_resol_device_information (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f45f88c6b90>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 256, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/deltasol/sensor.py", line 83, in async_update_data
    raise error
  File "/config/custom_components/deltasol/sensor.py", line 79, in async_update_data
    data = await hass.async_add_executor_job(api.fetch_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/deltasol/deltasolapi.py", line 107, in fetch_data
    raise error
  File "/config/custom_components/deltasol/deltasolapi.py", line 92, in fetch_data
    product = self.detect_product()
              ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/deltasol/deltasolapi.py", line 83, in detect_product
    raise IntegrationError(error)
homeassistant.exceptions.IntegrationError: Error detecting Resol product - HTTPConnectionPool(host='127.0.0.1', port=3333): Max retries exceeded with url: /cgi-bin/get_resol_device_information (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f45f88c6b90>: Failed to establish a new connection: [Errno 111] Connection refused')), please file an issue at: https://github.com/dm82m/hass-Deltasol-KM2/issues/new/choose

**Comment by evertterpstra** [comment]
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:360
Integration: Sensor (documentation, issues)
First occurred: February 6, 2024 at 15:01:06 (1 occurrences)
Last logged: February 6, 2024 at 15:01:06

Error while setting up deltasol platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/deltasol/sensor.py", line 98, in async_setup_platform
    await update_unique_ids(hass, coordinator.data)
  File "/config/custom_components/deltasol/sensor.py", line 58, in update_unique_ids
    for unique_id, endpoint in data.items():
                               ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'items'

**Comment by dm82m** [comment]
The integration is not getting a connection to your device. Seems that you are using the resol-vbus addon. Please check if that is running and check the logs of it.

**Comment by evertterpstra** [comment]
![fout](https://github.com/dm82m/hass-Deltasol-KM2/assets/123770708/bc412cf7-41ae-4d1c-a413-4561690d043b)
This in my Yaml, but I don't know where to find resol-vbus addon, still try to finf it in HA..............
Evert

**Comment by evertterpstra** [comment]
![fout3](https://github.com/dm82m/hass-Deltasol-KM2/assets/123770708/cdecd465-63c4-485c-b359-0addbbf8d958)
![fout2](https://github.com/dm82m/hass-Deltasol-KM2/assets/123770708/55e29d09-a831-4043-9205-56f5412bf9dc)

**Comment by evertterpstra** [comment]
did
![restart](https://github.com/dm82m/hass-Deltasol-KM2/assets/123770708/5a39b5e7-b1d5-4bc8-b138-dc58448db8d3)
 a restart...........

**Comment by dm82m** [comment]
Try to restart Home Assistant core. What device are you using of resil and how are you accessing the device with vbus-addon? It doesn’t seem that it is connection by usb so it’s a network device?

**Comment by evertterpstra** [comment]
> Try to restart Home Assistant core. What device are you using of resil and how are you accessing the device with vbus-addon? It doesn’t seem that it is connection by usb so it’s a network device?

I am using this: [KM2 Communication module - resol.de](https://www.resol.de/en/produktdetail/209)
Try to restart my HA........

**Comment by evertterpstra** [comment]
I don't know exactly what the problem is/was, but a fresh start of HA solved the problem............ 
Thnxs for your help dm82m! 
![opgelost](https://github.com/dm82m/hass-Deltasol-KM2/assets/123770708/d436f42e-df1e-42cb-bc55-16359fcec0da)

**Comment by dm82m** [comment]
okay glad that it worked. but to be honest, I dont understand your setup.

if you are using a KM2 device there is no need to use resol-vbus addon. instead you could just point the integration to the ip address of your KM2 device. and dont use a port.

```
sensor:
  - platform: deltasol
    host: your_resol_hostname_or_ip
    username: your_username
    password: your_password
```

**Comment by evertterpstra** [comment]
> okay glad that it worked. but to be honest, I dont understand your setup.
> 
> if you are using a KM2 device there is no need to use resol-vbus addon. instead you could just point the integration to the ip address of your KM2 device. and dont use a port.
> 
> ```
> sensor:
>   - platform: deltasol
>     host: your_resol_hostname_or_ip
>     username: your_username
>     password: your_password
> ```

Then I'll make this the new setup in Yaml...... Thnak you for answering and help with my setup of HA.
greetings from Scharmer, The Netherlands.
Evert

**Comment by dm82m** [comment]
usually I would say: never touch a running system. but if it is a KM2 then the use of resol-vbus only makes it way more complicated and way more error prone. so I would give it a try to natively connect the integration to the KM2 as described. and if that works turn off/remove resol-vbus add-on.
