### ISSUE TITLE
Unexpected error fetching deltasol_sensor data

### ISSUE THREAD

**Issue by evertterpstra** [dm82m/hass-Deltasol-KM2#39]
Hello need some help I update the new core and get these 3 errors:
![Screenshot 2024-03-09 092000](https://github.com/dm82m/hass-Deltasol-KM2/assets/123770708/493ebeae-9575-4f90-86ab-f72c635c6ebd)

This error originated from a custom integration.

Logger: custom_components.deltasol
Source: helpers/update_coordinator.py:318
integration: deltasol (documentation, issues)
First occurred: 08:57:04 (1 occurrences)
Last logged: 08:57:04

Unexpected error fetching deltasol_sensor data: Error detecting Resol product - HTTPConnectionPool(host='127.0.0.1', port=3333): Max retries exceeded with url: /cgi-bin/get_resol_device_information (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f4f746b10>: Failed to establish a new connection: [Errno 111] Connection refused')), please file an issue at: https://github.com/dm82m/hass-Deltasol-KM2/issues/new/choose
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.12/http/client.py", line 1331, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.12/http/client.py", line 1377, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.12/http/client.py", line 1326, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.12/http/client.py", line 1085, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.12/http/client.py", line 1029, in send
    self.connect()
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f8f4f746b10>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=3333): Max retries exceeded with url: /cgi-bin/get_resol_device_information (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f4f746b10>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/deltasol/deltasolapi.py", line 64, in detect_product
    response = requests.request("GET", url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=3333): Max retries exceeded with url: /cgi-bin/get_resol_device_information (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f4f746b10>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 318, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 274, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/deltasol/sensor.py", line 83, in async_update_data
    raise error
  File "/config/custom_components/deltasol/sensor.py", line 79, in async_update_data
    data = await hass.async_add_executor_job(api.fetch_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/deltasol/deltasolapi.py", line 107, in fetch_data
    raise error
  File "/config/custom_components/deltasol/deltasolapi.py", line 92, in fetch_data
    product = self.detect_product()
              ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/deltasol/deltasolapi.py", line 83, in detect_product
    raise IntegrationError(error)
homeassistant.exceptions.IntegrationError: Error detecting Resol product - HTTPConnectionPool(host='127.0.0.1', port=3333): Max retries exceeded with url: /cgi-bin/get_resol_device_information (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f4f746b10>: Failed to establish a new connection: [Errno 111] Connection refused')), please file an issue at: https://github.com/dm82m/hass-Deltasol-KM2/issues/new/choose

==========================================================================================

This error originated from a custom integration.

Logger: custom_components.deltasol
Source: custom_components/deltasol/sensor.py:82
integration: deltasol (documentation, issues)
First occurred: 08:57:04 (1 occurrences)
Last logged: 08:57:04

Stopping Resol integration due to previous error: Error detecting Resol product - HTTPConnectionPool(host='127.0.0.1', port=3333): Max retries exceeded with url: /cgi-bin/get_resol_device_information (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f4f746b10>: Failed to establish a new connection: [Errno 111] Connection refused')), please file an issue at: https://github.com/dm82m/hass-Deltasol-KM2/issues/new/choose

==========================================================================================

This error originated from a custom integration.

Logger: custom_components.deltasol
Source: custom_components/deltasol/deltasolapi.py:82
integration: deltasol (documentation, issues)
First occurred: 08:57:04 (1 occurrences)
Last logged: 08:57:04

Error detecting Resol product - HTTPConnectionPool(host='127.0.0.1', port=3333): Max retries exceeded with url: /cgi-bin/get_resol_device_information (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f4f746b10>: Failed to establish a new connection: [Errno 111] Connection refused')), please file an issue at: https://github.com/dm82m/hass-Deltasol-KM2/issues/new/choose

**Comment by dm82m** [comment]
Restart the addon „resol-vbus“ then restart home Assistant Core.

**Comment by evertterpstra** [comment]
Thnxs, that solved the problem!👍💪Verstuurd vanaf mijn iPhone, met vriendelijke groet,Evert TerpstraOp 9 mrt 2024 om 09:23 heeft Dirk ***@***.***> het volgende geschreven:﻿
Restart the addon „resol-vbus“ then restart home Assistant Core.
