### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by freddy357** [dm82m/hass-Deltasol-KM2#43]
--- VERSIONS ---
add-on version: 0.0.7
nodejs version: v22.3.0
npm version: 10.8.1
--- DEVICES ---
/dev/ttyUSB0
ls: cannot access '/dev/ttyACM*': No such file or directory
--- json-live-data-server ---
debug: Starting server...
debug: Connect to VBus data source...
error: Main function returned with error:
error: Error: Unable to connect
    at cleanup (/bin/resol-vbus/src/serial-connection.js:157:28)
    at SerialPort.onSerialPortError (/bin/resol-vbus/src/serial-connection.js:94:17)
    at SerialPort.emit (node:events:520:28)
    at SerialPort._error (/bin/resol-vbus/node_modules/@serialport/stream/dist/index.js:78:18)
    at /bin/resol-vbus/node_modules/@serialport/stream/dist/index.js:111:18

Logger: py.warnings
Source: util/loop.py:131
First occurred: 19:44:49 (1 occurrences)
Last logged: 19:44:49

/config/custom_components/deltasol/sensor.py:50: SyntaxWarning: invalid escape sequence '\d' vol.Optional(CONF_API_KEY): config_validation.matches_regex("\d\d"),

**Comment by dm82m** [comment]
Would say that your config file is not correct, this is more related to neolink, please file an issue at Andy’s repo: https://github.com/QuantumEntangledAndy/neolink/issues

**Comment by freddy357** [comment]
I will do that, thanks

Op do 13 jun 2024 om 19:56 schreef Dirk ***@***.***>:

**Comment by freddy357** [comment]
Oke so there is no neolink error or indication that it even tried to start neolink.

So do you now where i can solve this issue?


--- VERSIONS ---
add-on version: 0.0.7
nodejs version: v22.3.0
npm version: 10.8.1
--- DEVICES ---
/dev/ttyUSB0
/dev/ttyACM0
--- json-live-data-server ---
debug: Starting server...
debug: Connect to VBus data source...
error: Main function returned with error:
error: Error: Unable to connect
    at onSocketTermination (/bin/resol-vbus/src/tcp-connection.js:368:26)
    at Socket.onError (/bin/resol-vbus/src/tcp-connection.js:401:17)
    at Socket.emit (node:events:520:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by dm82m** [comment]
Please reinstall the addon so that you are on version 0.0.9

**Comment by dm82m** [comment]
Continues here: https://github.com/danielwippermann/resol-vbus/issues/103
